server:
  port: 8090

#data source
spring:
  datasource:
    username: root
    password: toor
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/comp_1640?autoReconnect=true&failOverReadOnly=false&maxReconnects=10"
    readUrl: "jdbc:mysql://localhost:3306/comp_1640?autoReconnect=true&failOverReadOnly=false&maxReconnects=10"
    showSql: false

    # hikari
    hikari:
      minimumIdle: 5
      maximumPoolSize: 500
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
      poolName: HikariPoolGraduationProject
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

localization:
  supportedLocales:
    - "vi"
    - "en"
  defaultLocale: "en"
  defaultMessage: "Undefined message"

jwt:
  privateKey: "MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgbOttWnN1S/hInMd7aFoQHFdhkzZj61/XSrc7QFx9unegCgYIKoZIzj0DAQehRANCAARk++lWyCaGNlbzqugMcJWDOmwv3n96QQ0uZK6FCI0JCGpveLIhmp3NPXKmHOEElnSfx8Bd738NlLb+IjGIjeRZ"
  publicKey: "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEZPvpVsgmhjZW86roDHCVgzpsL95/ekENLmSuhQiNCQhqb3iyIZqdzT1yphzhBJZ0n8fAXe9/DZS2/iIxiI3kWQ=="

multipart:
  uploadFileDir: "uploads"